### ISSUE TITLE
OBJECT:ACTION pattern in npm script names

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#1]
If npm scripts would be all called `OBJECT:ACTION` you could change

```json
    "prod": "npm-run-all delete:dist sass:prod eleventy:prod"
```

to

```json
    "prod:build": "npm-run-all prod:*"
```

I hope it doesn't fall into an infinite loop :)

**Comment by adamlaki** [comment]
Thanks Viktor, I will test it on local!

**Comment by adamlaki** [comment]
This is indeed works! Like the idea, give it a try: https://github.com/conedevelopment/cone-site/commit/8424ceb1693ab708c9feed5d571c55aaf05450c3

Thank!
