### ISSUE TITLE
Keeping OS, IDE and local environment gitignores on your local machine

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#2]
A single .gitignore file cannot cover every OS, every IDE and every local environment.
List your gitignores in a file: `~/.gitignore`
`git config --global core.excludesFile ~/.gitignore` will ignore all your local files in every project once and for all 🎉

**Comment by szepeviktor** [comment]
Only technologies used in this project should be listed in the repository.
```
# Dependencies
NPM stuff
# Application
Web stuff
# Tests
If there are tests ...
# Distribution
Files used for deploying this website
```

**Comment by adamlaki** [comment]
I don't understand this. What is the problem with the .gitignore file?

**Comment by szepeviktor** [comment]
> What is the problem with the .gitignore file?

It tries to cover every OS, every IDE and every local environment. That is impossible 💥 
All contributors should have their stuff ignored locally in `~/.gitignore`.

The project's `.gitignore` file should cover only the project's ignored files.

**Comment by szepeviktor** [comment]
🎈 It will be big Fun! Trust me.

**Comment by adamlaki** [comment]
Ahh, I get it and have a gif for this: https://media.giphy.com/media/bWM2eWYfN3r20/giphy.gif

**Comment by szepeviktor** [comment]
This is a single `~/.gitignore` file, you have to create once in your life.
```bash
git config --global core.excludesFile ~/.gitignore
```
