### ISSUE TITLE
Missing root files

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#21]
https://conedevelopment.com/favicon.ico

- robots.txt
- favicon.ico
- apple touch icons

These are downloaded **without** a link.

**Comment by szepeviktor** [comment]
There are a few hundred of this: https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Production-website.md
Please do not sleep for a week! 🙃

**Comment by szepeviktor** [comment]
Here we need a disallowing robots.txt https://cone-development-site.netlify.app
or a redirect to the live domain.
Search engines may index https://cone-development-site.netlify.app ...

_Netlify not being production ready makes viktor sad_

**Comment by adamlaki** [comment]
Yes, good points Viktor!

TODO:

- [ ] Add more favicon
- [ ] Add robots.txt
- [ ] Redirect netlify domain to live one

**Comment by adamlaki** [comment]
@szepeviktor the touch icons are also at the root?

**Comment by adamlaki** [comment]
https://github.com/conedevelopment/cone-site/commit/b94ea340d9492fbf1cd1cfbaad16212db95c06ca

**Comment by szepeviktor** [comment]
> a redirect to the live domain.

@adamlaki This does not work. Click https://cone-development-site.netlify.app/

**Comment by adamlaki** [comment]
Yeah, I've reverted it. I couldn't find how to do it. We have a site where this is working but we also have a lot others where we didn't bothered and still no Google index.

**Comment by szepeviktor** [comment]
> still no Google index

All right, all right.
Viktor goes and submits all your development sites to Google Search 🙃

**Comment by adamlaki** [comment]
Somehow, I can believe that. 🔥

**Comment by szepeviktor** [comment]
And right after that I cook cute kittens in my cauldron!

![image](https://github.com/conedevelopment/cone-site/assets/952007/688a6d01-251d-4e83-bb19-f1e679a4cdc1)

**Comment by szepeviktor** [comment]
Docs: https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects
Ordering matters.
