### ISSUE TITLE
Please do not minify previews

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#24]
e.g. https://deploy-preview-23--cone-development-site.netlify.app/

It makes spotting errors extra diffficult.

**Comment by szepeviktor** [comment]
There is a context env: https://docs.netlify.com/configure-builds/environment-variables/#build-metadata

**Comment by adamlaki** [comment]
https://github.com/conedevelopment/cone-site/commit/5ed00bb8174bc27d496c76bbe49e5eef2ca2c396
