### ISSUE TITLE
Accepting cookies on the thankyou page

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#25]
Accepting cookies on `/hu/sikeres-urlap-kuldes/` resends the POST request 😱

**Comment by adamlaki** [comment]
Can you give me more context Viktor? This should be a redirection, where is a resend?

**Comment by szepeviktor** [comment]
1. clear cookies
2. do not accept/reject cookies
3. navigate to the contact page
4. submit the contact form
5. accept cookies
6. 💥

**Comment by adamlaki** [comment]
Have you tried it in action, too? Because I didn't see duplicate submissions.

**Comment by szepeviktor** [comment]
Yes. Of course. Firefox asks me whether to resend the form.
