### ISSUE TITLE
Closing void tags

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#26]
Some [`<void />` elements](https://www.w3.org/TR/2011/WD-html-markup-20110113/syntax.html#syntax-elements) are closed, others are not: `<void>`.

May I send a PR to make them uniform?

> [!NOTE]
> grep '/>'

**Comment by adamlaki** [comment]
By HTML5, we don't need self-closing, so the mistake should be that. If you want to remove them - I also look out for them - then go for it.
