### ISSUE TITLE
[social image] Slack link previews don't work

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#27]
![image](https://github.com/conedevelopment/cone-site/assets/952007/9d1b6658-772d-4db5-800b-24a16d37bdaf)

https://slack.com/help/articles/204399343-Share-links-and-set-preview-preferences

**Comment by szepeviktor** [comment]
Linked but missing `img/social-share.png` 💥 
https://www.bannerbear.com/tools/twitter-card-preview-tool/

(I should really close those laser eyes 🙈)

**Comment by szepeviktor** [comment]
@adamlaki Netlify gives us back our vision if we pay $$$
https://docs.netlify.com/monitor-sites/log-drains/

> This feature is available on Enterprise [plans](https://www.netlify.com/pricing/#features-log-drains).

Access logs are available on $$$ plans.

**Comment by adamlaki** [comment]
Thanks Viktor!

https://github.com/conedevelopment/cone-site/commit/6f87f191b74e4328b01a68dc38c60afc26af548f
