### ISSUE TITLE
Wrong Vary: HTTP header

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#32]
https://redbot.org/?uri=https://conedevelopment.com/hu/

The `Vary` header should always contain `accept-encoding` but it does not.

**Comment by szepeviktor** [comment]
I may have dug too deep.
This reveals the true face of Netlify.

Anyone to contact their customer support?

**Comment by adamlaki** [comment]
Nope. I don't think that this is something we could or should do anything. It is what it is.
