### ISSUE TITLE
Cone Hosting: weboldal, webáruház, alkalmazás

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#59]
@adamlaki @iamgergo Lehetne egy új infrastruktúra szolgáltatás?
Mögöttetek én dolgoznék.

https://github.com/conedevelopment/cone-site/blob/71bcd5de8a6e5e2a954deaed09df53859457d8c7/src/hu/szolgaltatasaink.md?plain=1#L15

**Comment by szepeviktor** [comment]
domain reg, DNS, szerver, SSL tanúsítvány, CDN, email küldő, biztonsági mentés - €30/hó
viktor gondoskodás - valami kajára (másoknak 30e/hó)

https://github.com/szepeviktor/debian-server-tools/blob/master/Onboarding.md#specialized-infrastructure-providers

**Comment by adamlaki** [comment]
@szepeviktor Szia Viktor,

mi benne lennénk egy hasonló felállásban. Előtte kell még sok mindent tisztázni, hogy pontosan átlássuk, hogy mit kínálunk, kiket célzunk, kinek lehet eladni. Meg persze azt is, hogy neked pontosan mi felel meg.

Jövő héten valamikor egy megbeszélés a pontos részletekről?

**Comment by szepeviktor** [comment]
Nekem bármi megfelel, az is SOKKAL jobb, ha 1000 forintért dolgozok, mintha nem dolgozok.

Az egész jövő hetet pont erre szántam. Küldd a meghívót!

**Comment by adamlaki** [comment]
Remek, küldtem az előbb egy meghívót szerdán 10:00-re!

**Comment by szepeviktor** [comment]
ezeket emelném ki

1. üzembiztonság - évi 1 vagy 2 üzemzavarral
2. betörés biztonság - nem törik fel
3. sebesség - 0,2-0,5 mp-es oldal generálás

**Comment by szepeviktor** [comment]
@adamlaki Beszélgettem egyet a Kinsta-ékkal.
A PHP OPcache-t megkérdezi, felteszem lesz lehetőség rá.
A Redis

# havi $100-ba

kerül.

**Comment by adamlaki** [comment]
@szepeviktor Kinstánál havi $100 plusz ha akarsz Redis-t? :O Vagy hogy érted?

**Comment by szepeviktor** [comment]
> Kinstánál havi $100 plusz ha akarsz Redis-t?

@adamlaki Igen.
https://kinsta.com/add-ons/#h-redis

- nincs benne a support a Redis-hez
- el is magyarázzák neked, hogy miért nem kell Redis egy egyszerű oldalhoz
