### ISSUE TITLE
markdownlint-cli2 keeps Markdown code in check

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/cone-site#7]
`npx markdownlint-cli2 'src/**.md'`

Front matter could be checked with yamllint.

Should we obey an absolute line length limit? 120/300/1000?

**Comment by adamlaki** [comment]
I will check this local. I don't think we need an absolute line length limit!

Thank you!

**Comment by szepeviktor** [comment]
Okay.

> Too much liberty makes you ill.

_source unknown_
